# Generated by Django 4.1.5 on 2023-01-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_question_option3_question_option4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
